plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.140'
    id 'net.darkhax.curseforgegradle' version '1.1.24'
    id "com.modrinth.minotaur" version "2.+"
}

version = "${minecraft_version}-${mod_version}"
group = mod_group_id

repositories {
    mavenLocal()

    maven {
        name = "Curse Maven"
        url = uri("https://cursemaven.com")
        content {
            includeGroup("curse.maven")
        }
    }

    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
}
base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = project.neo_version

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
        }

        client {
            client()
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
            programArgument '--nogui'
        }

        clientData {
            clientData()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {

    //JEI
    implementation("mezz.jei:jei-${jei_mc_version}-neoforge:${jei_version}")
    //Connectivity
    runtimeOnly("curse.maven:connectivity-470193:7866655")
    //Cupboard
    runtimeOnly("curse.maven:cupboard-326652:7904113")
    //KubeJS
    implementation("curse.maven:kubejs-238086:8235730")
    //Rhino
    implementation("curse.maven:rhino-416294:8218748")
    //BBL Core
    implementation("curse.maven:bbl-core-1135181:8220864")
    //BBL Strainers
    implementation("curse.maven:bbl-strainers-882351:8294402")
    //BBL Utility
    implementation("curse.maven:bbl-utility-649644:8221171")
    //Cucumber Core
    implementation("curse.maven:cucumber-272335:8178456")
    //Cucumber Core
    implementation("curse.maven:mystical-agriculture-246640:8130326")
    //Horse Powered
    implementation("curse.maven:horse-powered-1408330:8158328")
    //AE2
    implementation("curse.maven:applied-energistics-2-223794:8129795")
    //Guide ME
    implementation("curse.maven:guideme-1173950:8204880")
    //Infinity Drives
    implementation("curse.maven:infinity-drives-1386843:8103133")
    //Cloche
    implementation("curse.maven:bbl-cloche-1153960:8128509")
    //Powah Rearchitected
    implementation("curse.maven:powah-rearchitected-633483:8025339")
    //Cloth Config
    implementation("curse.maven:cloth-config-348521:7817583")
    //Ender IO
    implementation("curse.maven:ender-io-64578:8192909")

}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {

        maven {
            url "https://cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }

        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}