# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4608M
org.gradle.daemon=false
org.gradle.debug=false

## Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.74
neo_version_range=[26.1.2.74,)
loader_version_range=[4,)

## Mod Properties
mod_id=schemajs
mod_name=Schema JS
mod_license=MIT
mod_version=1.3.4
mod_group_id=com.benbenlaw.schemajs
mod_authors=benbenlaw
mod_description=Tried to add as many schemas for KubeJS to support various mods.

jei_mc_version=26.1.2
jei_version=29.6.2.31

## Auto Updates
curseforge_id=1547021
modrinth_id=y3wDZvHy